#!/bin/bash
export LC_NUMERIC="en_US.UTF-8"

function help {
  echo "Create LSG topogr file with constant depth"
  echo "Usage: maketopo [OPTIONS] depth"
  echo "   depth : the constant depth in [m]"
  exit 1
}

DEPTH=$1
if [ $# -lt 1 ]; then
   help
fi

cat << EOF
(f4.0)
 10.
(10f10.2)
    -99.00     72.00     76.00      5.00      2.50      6.25     93.75      1.00 881201.00 211003.00
(9f8.2)
EOF

for ((i=1; i<=608; i++)); do
   for ((j=1; j<=9; j++)); do
       printf "%8.2f" $DEPTH
   done
   echo 
done
